<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260606180741 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adding the action attribute in Tickets Entity with Relation ManyToOne';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE action (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(150) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE ticket ADD action_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket ALTER priority TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE ticket ALTER priority DROP DEFAULT');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA39D32F035 FOREIGN KEY (action_id) REFERENCES action (id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA39D32F035 ON ticket (action_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE action');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA39D32F035');
        $this->addSql('DROP INDEX IDX_97A0ADA39D32F035');
        $this->addSql('ALTER TABLE ticket DROP action_id');
        $this->addSql('ALTER TABLE ticket ALTER priority TYPE VARCHAR(25)');
        $this->addSql('ALTER TABLE ticket ALTER priority SET DEFAULT \'medium\'');
    }
}
