<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260606160843 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add core relationships to Ticket entity (User, Department, Category, TicketType) and inject TicketPriority enum.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE departament (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ticket_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, full_name VARCHAR(150) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE ticket ADD priority VARCHAR(25) DEFAULT \'medium\' NOT NULL');
        $this->addSql('ALTER TABLE ticket ADD meta_data JSONB NOT NULL');
        $this->addSql('ALTER TABLE ticket ADD category_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket ADD requester_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket ADD assigned_to_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket ADD departament_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket ADD ticket_type_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA312469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3ED442CF4 FOREIGN KEY (requester_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3F4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA348B3EEE4 FOREIGN KEY (departament_id) REFERENCES departament (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3C980D5C1 FOREIGN KEY (ticket_type_id) REFERENCES ticket_type (id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA312469DE2 ON ticket (category_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA3ED442CF4 ON ticket (requester_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA3F4BD7827 ON ticket (assigned_to_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA348B3EEE4 ON ticket (departament_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA3C980D5C1 ON ticket (ticket_type_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE departament');
        $this->addSql('DROP TABLE ticket_type');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA312469DE2');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA3ED442CF4');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA3F4BD7827');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA348B3EEE4');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA3C980D5C1');
        $this->addSql('DROP INDEX IDX_97A0ADA312469DE2');
        $this->addSql('DROP INDEX IDX_97A0ADA3ED442CF4');
        $this->addSql('DROP INDEX IDX_97A0ADA3F4BD7827');
        $this->addSql('DROP INDEX IDX_97A0ADA348B3EEE4');
        $this->addSql('DROP INDEX IDX_97A0ADA3C980D5C1');
        $this->addSql('ALTER TABLE ticket DROP priority');
        $this->addSql('ALTER TABLE ticket DROP meta_data');
        $this->addSql('ALTER TABLE ticket DROP category_id');
        $this->addSql('ALTER TABLE ticket DROP requester_id');
        $this->addSql('ALTER TABLE ticket DROP assigned_to_id');
        $this->addSql('ALTER TABLE ticket DROP departament_id');
        $this->addSql('ALTER TABLE ticket DROP ticket_type_id');
    }
}
