@hostname = http://localhost:8000/api

# IMPORTANTE: Para que o POST abaixo funcione, certifique-se de ter rodado 
# a criação inicial de pelo menos um registro com ID 1 nos outros arquivos .http.

# @name createTicket
POST {{hostname}}/tickets
Content-Type: application/ld+json

{
    "title": "Mouse parou de responder no setor",
    "description": "O periférico parou de funcionar subitamente no meio do expediente.",
    "priority": "medium",
    "category": "/api/categories/1",
    "requester": "/api/users/1",
    "departament": "/api/departaments/1",
    "ticketType": "/api/ticket_types/1",
    "action": "/api/actions/1",
    "metaData": {
        "patrimonio": "RBS-99832",
        "so": "Fedora KDE"
    }
}

###

# @name getTickets
GET {{hostname}}/tickets
Accept: application/ld+json

###

# @name updateTicketPriority
PATCH {{hostname}}/tickets/1
Content-Type: application/merge-patch+json

{
    "priority": "high"
}

###

# @name assignTicket
PATCH {{hostname}}/tickets/1
Content-Type: application/merge-patch+json

{
    "assignedTo" : "/api/users/5",
    "status" : "in_progress"
}

###

# @name cancelTicket
PATCH {{hostname}}/tickets/1
Content-Type: application/merge-patch+json

{
    "status": "cancelled"
}

###

# @name suspendTicket
PATCH {{hostname}}/tickets/1
Content-Type: application/merge-patch+json

{
    "status": "suspend"
}

###

# @name deleteTicket
DELETE {{hostname}}/tickets/1